version: '2.0'
name: 'database'

services:
  postgres:
    image: postgres:13
    restart: unless-stopped
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: securedatabase

  pgadmin:
    container_name: pgAdmin
    image: dpage/pgadmin4:7.5
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-rafekzielinski@wp.pl}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - postgres
networks:
  postgres:
    driver: bridge